# Generated by Django 4.2.6 on 2023-10-15 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="имя")),
                (
                    "directory",
                    models.CharField(
                        max_length=200, verbose_name="директория"
                    ),
                ),
            ],
            options={
                "verbose_name": "меню",
                "verbose_name_plural": "меню",
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="имя")),
                (
                    "directory",
                    models.CharField(
                        max_length=200, verbose_name="директория"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, null=True, verbose_name="адрес"
                    ),
                ),
                ("is_root", models.BooleanField(verbose_name="корневой")),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=1,
                        null=True,
                        verbose_name="уровень",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="menus.menu",
                        verbose_name="меню",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="menus.menuitem",
                        verbose_name="родительский элемент",
                    ),
                ),
            ],
            options={
                "verbose_name": "элемент меню",
                "verbose_name_plural": "элементы меню",
            },
        ),
        migrations.AddField(
            model_name="menu",
            name="root_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="menu_base",
                to="menus.menuitem",
                verbose_name="корневой элемент",
            ),
        ),
    ]
