# Generated by Django 4.2.6 on 2023-10-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="адрес"),
        ),
    ]
